
export const communities = {
    "01": "Andalucía",
    "02": "Aragón",
    "03": "Asturias, Principado de",
    "04": "Balears, Illes",
    "05": "Canarias",
    "06": "Cantabria",
    "07": "Castilla y León",
    "08": "Castilla - La Mancha",
    "09": "Cataluña",
    "10": "Comunitat Valenciana",
    "11": "Extremadura",
    "12": "Galicia",
    "13": "Madrid, Comunidad de",
    "14": "Murcia, Región de",
    "15": "Navarra, Comunidad Foral de",
    "16": "País Vasco",
    "17": "Rioja, La",
    "18": "Ceuta",
    "19": "Melilla"
};

export const provinces = {
    "01": { name: "Araba/Álava", ca: "16" },
    "02": { name: "Albacete", ca: "08" },
    "03": { name: "Alicante/Alacant", ca: "10" },
    "04": { name: "Almería", ca: "01" },
    "05": { name: "Ávila", ca: "07" },
    "06": { name: "Badajoz", ca: "11" },
    "07": { name: "Balears, Illes", ca: "04" },
    "08": { name: "Barcelona", ca: "09" },
    "09": { name: "Burgos", ca: "07" },
    "10": { name: "Cáceres", ca: "11" },
    "11": { name: "Cádiz", ca: "01" },
    "12": { name: "Castellón/Castelló", ca: "10" },
    "13": { name: "Ciudad Real", ca: "08" },
    "14": { name: "Córdoba", ca: "01" },
    "15": { name: "Coruña, A", ca: "12" },
    "16": { name: "Cuenca", ca: "08" },
    "17": { name: "Girona", ca: "09" },
    "18": { name: "Granada", ca: "01" },
    "19": { name: "Guadalajara", ca: "08" },
    "20": { name: "Gipuzkoa", ca: "16" },
    "21": { name: "Huelva", ca: "01" },
    "22": { name: "Huesca", ca: "02" },
    "23": { name: "Jaén", ca: "01" },
    "24": { name: "León", ca: "07" },
    "25": { name: "Lleida", ca: "09" },
    "26": { name: "Rioja, La", ca: "17" },
    "27": { name: "Lugo", ca: "12" },
    "28": { name: "Madrid", ca: "13" },
    "29": { name: "Málaga", ca: "01" },
    "30": { name: "Murcia", ca: "14" },
    "31": { name: "Navarra", ca: "15" },
    "32": { name: "Ourense", ca: "12" },
    "33": { name: "Asturias", ca: "03" },
    "34": { name: "Palencia", ca: "07" },
    "35": { name: "Palmas, Las", ca: "05" },
    "36": { name: "Pontevedra", ca: "12" },
    "37": { name: "Salamanca", ca: "07" },
    "38": { name: "Santa Cruz de Tenerife", ca: "05" },
    "39": { name: "Cantabria", ca: "06" },
    "40": { name: "Segovia", ca: "07" },
    "41": { name: "Sevilla", ca: "01" },
    "42": { name: "Soria", ca: "07" },
    "43": { name: "Tarragona", ca: "09" },
    "44": { name: "Teruel", ca: "02" },
    "45": { name: "Toledo", ca: "08" },
    "46": { name: "Valencia/València", ca: "10" },
    "47": { name: "Valladolid", ca: "07" },
    "48": { name: "Bizkaia", ca: "16" },
    "49": { name: "Zamora", ca: "07" },
    "50": { name: "Zaragoza", ca: "02" },
    "51": { name: "Ceuta", ca: "18" },
    "52": { name: "Melilla", ca: "19" }
};
